### PR TITLE
Truffler 2.0

### PR DESCRIPTION
**Pull request by rowanmanning**
See the [Migration Guide](https://github.com/nature/truffler/blob/2.x/MIGRATION.md) and the [README](https://github.com/nature/truffler/blob/2.x/README.md) for information on what Truffler 2.0 changes.

Before:
```js
truffler({
    testFunction: function (browser, page, done) {
        // the test function to run in PhantomJS
        done();
    }
}, function (error, test, exit) {
    test('http://www.nature.com/', function (error, results) {
        console.log(results);
        exit();
    });
});
```

After:
```js
var test = truffler(function (browser, page, done) {
    // the test function to run in PhantomJS
    done();
});

test.run('http://www.nature.com/', function (error, results) {
    console.log(results);
});
```

### CODE REVIEW

**Comment by whymarrh** [comment]
Hey @rowanmanning, you're missing a description :)

I took a brief look through the changes here and #3, and this looks good—I like the look of the new API quite a bit (e.g. moving what was the `testFunction` option into a proper argument and returning the test function). Passing around a truffler instance will be nice and easy now.

How do you think these updates will affect the pa11y API? Also, I'm curious about how the issues with zombies reoccurred—maybe it's worth adding a note to the README file?

**Comment by whymarrh** [comment]
Adding an example with multiple tests that doesn't use async (similar to what's in the README) might be useful. I think the new API makes it a lot easier to run multiple tests without the async lib and deserves to be shown off.

**Comment by rowanmanning** [comment]
Hey @whymarrh, yes I am missing a description! I've been on one with the coding.

Thanks for your feedback, it's nice to get confirmation on the API – I thought it seemed much more sensible and easier to extend. I think next steps (once 2.0 is released) will be to build multiple test-runners into core. Maybe like this:

```js
test.run([
    'nature.com',
    'nature.com/nplants'
], function(error, results) {
    // ...
})
```

In the shorter term, I'd happily accept a PR adding a non-async example. Depends whether you want to if we're potentially adding multi-tests into core anyway :)

---

> How do you think these updates will affect the pa11y API?

I'm probably going to update the pa11y API to match this one and roll version 3.0. The current API is quite cack-handed, I think. I kind of overcomplicated it. The new one would look like this:

```js
var test = pa11y({
    standard: 'WCAG2AA'
});

test.run('nature.com', function(error, results) {
    // ...
});
```

It's going to require a bit of an overhaul of the tests, but it simplifies pa11y quite a lot – some of the heavy lifting (timeouts, for example) has moved into Truffler.

---

> Also, I'm curious about what the issues with zombies looked like&hellip;

I'm still debugging zombie issues right now, and I think that most of it is to do with the old PhantomJS bridge. This week coming up I'd like to put together an updated branch of the dashboard – the CLI seems fine but the dashboard we run internally keeps eating up all the server's memory with zombie processes.

It'll take a little bit of tweaking and monitoring to verify that it's fixed. I have a feeling that at least part of the issue was actually in the way that timeouts were handled, when the client-side part of pa11y is cut off mid-flow. If that's the case, I might also be able to improve the stability of the 2.x branch down the line, but we'll see.

It'll be annoying if it turns out to _not_ be the bridge, but I think it's worth updating anyway. It's much easier to support future versions of Node.js if none of the dependencies have V8 bindings!

**Comment by whymarrh** [comment]
When you do settle on a fix for the dashboard, that might be something worth writing up.

**Comment by moddular** [comment]
:+1:

**Pull request merged**
